### ISSUE TITLE
failed to load source for dependency `struct-tracker`

### ISSUE THREAD

**Issue by pethil** [AaronErhardt/relm4#2]
I tried running one of the examples as is and got the following:

```
cargo run --example trackers
    Updating crates.io index
    Updating git repository `https://github.com/AaronErhardt/Struct-Tracker`
error: failed to get `struct-tracker` as a dependency of package `relm4 v0.1.0 (/var/home/peter/relm4)`

Caused by:
  failed to load source for dependency `struct-tracker`

Caused by:
  Unable to update https://github.com/AaronErhardt/Struct-Tracker

Caused by:
  failed to find branch `master`

Caused by:
  cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3)
```

**Comment by AaronErhardt** [comment]
Thanks for your feedback. That issue should only appear on cargo versions below 1.53 which is the current stable so I didn't notice. Before that release cargo expected master to be the default branch name which isn't the case with struct-tracker because GitHub now uses main by default.

With the latest commit I added an explicit branch name which should fix this issue for everyone. Let me know if you can now run the example so I can close this issue :)

**Comment by pethil** [comment]
Cool, that issue is gone now.
