### ISSUE TITLE
widget macro doesn't work with reexports

### ISSUE THREAD

**Issue by mskorkowski** [AaronErhardt/relm4#34]
I've created a library crate with bunch of reexports to have one place to rule all external dependencies related to relm and gtk.

```rust
pub use gtk;
pub use gtk::glib as glib;
pub use libadwaita;
pub use relm4;
pub use relm4_macros;
pub use relm4_components;
pub use tracker;
```

If I use relm widget macro from my reexports I receive

```
    | #[relm4_macros::widget(pub)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `relm4`
    |
    = note: this error originates in the attribute macro `relm4_macros::widget` (in Nightly builds, run with -Z macro-backtrace for more info)
    | #[widget(pub)]
    | ^^^^^^^^^^^^^^ could not find `gtk` in the list of imported crates
    |
    = note: this error originates in the attribute macro `widget` (in Nightly builds, run with -Z macro-backtrace for more info)
```

If I build my app with `-Z macro-backtrace` then it points to `lib.rs:105` in `relm4-macros`.

Even adding use for `gtk` and `relm4` like below doesn't help.

```rust
use my_reexports::gtk;
use my_reexports::relm4;
```

Is only workaround to abandon widget macro?

**Comment by AaronErhardt** [comment]
The error makes sense because it's recommended for proc macros to use `::relm4` or `::gtk` for imports so they don't accidentally use the wrong trait in case it comes to naming conflicts, for example if you add a module named `gtk` (https://doc.rust-lang.org/reference/procedural-macros.html#procedural-macro-hygiene). Yet, I wonder if in the case of the widget macro this isn't necessary because naming conflicts are very unlikely...

**Comment by AaronErhardt** [comment]
@mskorkowski any thoughts on this issue? Do you think it's worth to change the widget macro to work with re-exports?

**Comment by mskorkowski** [comment]
Sorry for late replay. I'm agains breaking hygiene of `widget` macro. Having things done at random in macros is asking for tickets here. I'm annoying enough 😉. I was trying to make relm4-macros support the syntax like

```rust
#[widget(pub, ::my_reexports::smth as relm4, ::my_reexports::smth_else as gtk)]
```

and propose the PR but while I could parse the arguments InputStream and extend Attrs, I didn't manage to work around code generation errors yet (this is my first time playing with macros for real). I'm getting invalid token errors.

List of requirements I thought of:

1. No changes are needed in existing code, so `#[widget()]` and `#[widget(pub)]` must work as is
2. New arguments must default to `::relm4` and `::gtk`
3. All arguments are optional
4. No order of arguments is implied, so `pub, ...as relm4, ...as gtk`, or `..as relm4, pub, ...as gtk`, or any other order must work

Other option I considered was to create `unhygenic_widget` macro. Would still work, but for me it looks like ugly compared to first solution.

**Comment by AaronErhardt** [comment]
That sounds great! Btw. the gtk imports don't seem to be necessary and probably can be replaced by relm4 paths: `::gtk::glib::Sender` to `::relm4::Sender` because Relm4 re-exports this type. Also make sure your version is up to date, I pushed changes to the macro yesterday (that will make it a bit easier for you, I guess).

At this point, I think we should add proper argument names to the macro to make it more clear. Something like this:

```rust
#[widget(visibility = pub, relm4 = ::my_reexports::smth)]
```
Let me know if I can help you with parsing or code generation :)

**Comment by mskorkowski** [comment]
I've rised PR which adds `#[widget(visibility = pub)]` syntax. Now I know what I was doing wrong so the rest should follow pretty soon.

**Comment by mskorkowski** [comment]
Since PR got merged, when do you plan to do the release?

**Comment by AaronErhardt** [comment]
A 0.2-beta release would be an option as well, that could be used in the meantime. What do you think?

**Comment by AaronErhardt** [comment]
Fixed with https://github.com/AaronErhardt/relm4/pull/37
