### ISSUE TITLE
Inconsistent behavior between FactoryVec and FactoryVecDeque

### ISSUE THREAD

**Issue by euclio** [AaronErhardt/relm4#57]
I'm trying to create a widget that adds and removes an arbitrary number of children at the position before some hard-coded widgets. I tried modifying the factory example like so:

```rust
        gtk::ApplicationWindow {
            set_default_width: 300,
            set_default_height: 200,
            set_child = Some(&gtk::Box) {
                set_orientation: gtk::Orientation::Vertical,
                set_margin_all: 5,
                set_spacing: 5,
                factory!(model.counters),
                append = &gtk::Button {
                    set_label: "Add",
                    connect_clicked(sender) => move |_| {
                        send!(sender, AppMsg::Add);
                    }
                },
                append = &gtk::Button {
                    set_label: "Remove",
                    connect_clicked(sender) => move |_| {
                        send!(sender, AppMsg::Remove);
                    }
                },
                append = &gtk::Button {
                    set_label: "I'M LAST",
                },
            }
        }
```

If I use `FactoryVec` for my storage, the new widgets are added and removed at the *last* position (after the "I'M LAST" label). However, if I use `FactoryVecDeque` for my storage, the widgets are added at the *first* position (before the "Add" button). The latter behavior happens to be what I want, but I wanted to open this issue to see if this is something I can rely on, or if there's a better way to accomplish what I want.

**Comment by AaronErhardt** [comment]
The reason why this happens is because there are different traits used behind the scenes. [FactoryView](https://aaronerhardt.github.io/docs/relm4/relm4/factory/trait.FactoryView.html) is used by both but [FactoryListView](https://aaronerhardt.github.io/docs/relm4/relm4/factory/trait.FactoryListView.html) is only required by `FactoryVecDeque` to enable more flexibility. That's because a Vec can only push and pop at the end whereas the VecDeque needs to take care about positioning. Since not all widgets support arbitrary positions both traits exist to at least allow `FactoryVec` to be used.

This also causes `FactoryVec` to use `append` to insert widgets and `FactoryVecDeque` uses `insert_after` unless it's the first widget. Of course it's better to use a separate container only for your factory but I'm pretty sure that this behaviour won't change anytime soon.

**Comment by euclio** [comment]
> Of course it's better to use a separate container only for your factory

Agreed, but in this case I need the children to all be children of the same widget (a PanelPaned from libpanel).

**Comment by AaronErhardt** [comment]
I'd suggest then to document the current behaviour. Any change to this (which is not very likely to happen anyway) would then be avoided or at least considered a breaking change.

**Comment by AaronErhardt** [comment]
The behavior is now documented: https://aaronerhardt.github.io/docs/relm4/relm4/factory/collections/index.html
