### ISSUE TITLE
Unable to use expressions that start with literals in the view macro

### ISSUE THREAD

**Issue by cofee-on-the-desk** [AaronErhardt/Relm4#90]
I can't use expressions that start with literals in the view macro, after the `:`, for some reason.

```rust
relm4::view! {
        mut vec = Vec::new() {
            push: "foo".to_string(),
        }
    }
```

This fails:
```rust
error: expected `,`. Did you confuse `=` with`:`?
  --> src\main.rs:57:24
   |
57 |             push: "foo".to_string(),
   |                        ^
```

Any other usage of literals seems to work fine, the following examples compile:

```rust
let s = "foo".to_string();
relm4::view! {
    mut vec = Vec::new() {
        push: s, // variable
    }
}
```

```rust
relm4::view! {
        mut vec = Vec::new() {
            push: (|| "foo".to_string())(), // closure (conditions and loops also work)
        }
    }
```

```rust
relm4::view! {
        mut vec = Vec::new() {
            push: "foo", // just the literal
        }
    }
```

The same problem with number and boolean literals.
The issue exists on both 0.4 and the latest git.

**Comment by AaronErhardt** [comment]
Again, thanks for letting me know. This seems to be caused by the parsing logic of syn's expression type that terminates before the dot. You should be able to avoid this by using brackets or parenthesis, a closure works too, but is a bit overkill for this kind of problem.

That said, it would be more convenient if brackets or parenthesis weren't needed so I will try to improve this soon.

**Comment by AaronErhardt** [comment]
So actually there was a part of the macro that parsed literals where I thought whole expressions were parsed. I've removed that now, so parsing literals should also parse the rest of the expression correctly.
